services:

    LSB\PricelistBundle\Form\PricelistType:
        tags:
            - {name: form.type}

    LSB\PricelistBundle\Form\PricelistPositionType:
        tags:
            - {name: form.type}

    LSB\PricelistBundle\Form\PricelistProductListType:
        tags:
            -
                name: form.type
        #   FIXME: Poprawna forma zapisu:
        #  - {name: form.type}
