services:

    LSB\PricelistBundle\Form\PricelistType:
        tags:
            - {name: form.type}

    LSB\PricelistBundle\Form\PricelistPositionType:
        tags:
            - {name: form.type}
