services:

    LSB\PricelistBundle\Repository\PricelistRepository:
        arguments:
            - '@doctrine'
    LSB\PricelistBundle\Repository\PricelistRepositoryInterface: '@LSB\PricelistBundle\Repository\PricelistRepository'

    LSB\PricelistBundle\Repository\PricelistPositionRepository:
        arguments:
            - '@doctrine'
    LSB\PricelistBundle\Repository\PricelistPositionRepositoryInterface: '@LSB\PricelistBundle\Repository\PricelistPositionRepository'

    LSB\PricelistBundle\Repository\PricelistProductListRepository:
        arguments:
            - '@doctrine'
    LSB\PricelistBundle\Repository\PricelistProductListRepositoryInterface: '@LSB\PricelistBundle\Repository\PricelistProductListRepository'
