language: php

php:
    - 8.0

matrix:
    fast_finish: true
    include:
        - php: 8.0

sudo: false

cache:
    directories:
        - $HOME/.composer/cache/files

install:
    - composer global require scrutinizer/ocular
    - composer update --prefer-dist --no-interaction

script:
    # - composer validate --strict --no-check-lock
    - XDEBUG_MODE=coverage vendor/bin/phpunit --coverage-clover=coverage.clover
    - ~/.composer/vendor/bin/ocular code-coverage:upload --format=php-clover coverage.clover
